version: '3.8'

services:
  # Service for the Spring Boot Application
  app:
    image: sanket164/promptly:backend
    container_name: promptly-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=promptly
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/promptly
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql
    networks:
      - promptly-network

  # Service for the MySQL Database
  mysql:
    image: mysql:latest
    container_name: promptly-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: promptly
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - promptly-network

# Define the network for communication between containers
networks:
  promptly-network:
    driver: bridge

# Define the volume for persistent MySQL data
volumes:
  mysql-data: