version: '3.8'

services:
  # Service for the Spring Boot Application
  app:
    image: sanket164/prompthub:backend
    container_name: prompthub-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=prompthub
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/prompthub
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql
    networks:
      - prompthub-network

  # Service for the MySQL Database
  mysql:
    image: mysql:latest
    container_name: prompthub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prompthub
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - prompthub-network

# Define the network for communication between containers
networks:
  prompthub-network:
    driver: bridge

# Define the volume for persistent MySQL data
volumes:
  mysql-data: